batch_size: 2
config: ./configs/baseline.yaml
dataset: phoenix14
dataset_info:
  dataset_root: C:\Users\Tugce\Documents\Datasets\PHOENIX-2014-T
  dict_path: ./preprocess/phoenix2014/gloss_dict.npy
  evaluation_dir: ./evaluation/slr_eval
  evaluation_prefix: phoenix2014-groundtruth
decode_mode: beam
device: 0,1
eval_interval: 1
evaluate_tool: sclite
feeder: dataset.dataloader_video.BaseFeeder
feeder_args:
  datatype: video
  drop_ratio: 1.0
  mode: train
  num_gloss: -1
ignore_weights: []
load_checkpoints: null
load_weights: C:/Users/Tugce/Documents/github/VAC_CSLR/resnet18_slr_pretrained_distill25.pt
log_interval: 50
loss_weights:
  SeqCTC: 1.0
model: slr_network.SLRModel
model_args:
  c2d_type: resnet18
  conv_type: 2
  num_classes: 1296
  share_classifier: false
  use_bn: 1
  weight_norm: false
num_epoch: 40
num_worker: 10
optimizer_args:
  base_lr: 0.0001
  learning_ratio: 1
  nesterov: false
  optimizer: Adam
  start_epoch: 0
  step:
  - 20
  - 35
  weight_decay: 0.0001
phase: features
print_log: true
random_fix: true
random_seed: 0
save_interval: 5
test_batch_size: 8
work_dir: ./work_dir/baseline_res18/
